spring.config.activate.on-profiles: database

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/wanted_internship?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}